# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmodels.proto\"e\n\x0cPublishDgram\x12\x0b\n\x03seq\x18\x01 \x02(\r\x12\n\n\x02ts\x18\x02 \x02(\x04\x12\x0f\n\x07request\x18\x03 \x01(\x08\x12\r\n\x05topic\x18\x04 \x02(\t\x12\x0b\n\x03\x61\x63k\x18\x05 \x03(\r\x12\x0f\n\x07payload\x18\x06 \x02(\x0c\"v\n\x0fPublishAckDgram\x12\x0b\n\x03seq\x18\x01 \x02(\r\x12\n\n\x02T2\x18\x02 \x02(\x04\x12\n\n\x02T3\x18\x03 \x01(\x04\x12\x11\n\trespondto\x18\x04 \x01(\r\x12\x0b\n\x03\x61\x63k\x18\x05 \x03(\r\x12\r\n\x05\x61\x63kT2\x18\x06 \x03(\x04\x12\x0f\n\x07payload\x18\x07 \x01(\x0c'
)




_PUBLISHDGRAM = _descriptor.Descriptor(
  name='PublishDgram',
  full_name='PublishDgram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='PublishDgram.seq', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ts', full_name='PublishDgram.ts', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='PublishDgram.request', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='PublishDgram.topic', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack', full_name='PublishDgram.ack', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PublishDgram.payload', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=117,
)


_PUBLISHACKDGRAM = _descriptor.Descriptor(
  name='PublishAckDgram',
  full_name='PublishAckDgram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='PublishAckDgram.seq', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='T2', full_name='PublishAckDgram.T2', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='T3', full_name='PublishAckDgram.T3', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='respondto', full_name='PublishAckDgram.respondto', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack', full_name='PublishAckDgram.ack', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ackT2', full_name='PublishAckDgram.ackT2', index=5,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PublishAckDgram.payload', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=237,
)

DESCRIPTOR.message_types_by_name['PublishDgram'] = _PUBLISHDGRAM
DESCRIPTOR.message_types_by_name['PublishAckDgram'] = _PUBLISHACKDGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublishDgram = _reflection.GeneratedProtocolMessageType('PublishDgram', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHDGRAM,
  '__module__' : 'models_pb2'
  # @@protoc_insertion_point(class_scope:PublishDgram)
  })
_sym_db.RegisterMessage(PublishDgram)

PublishAckDgram = _reflection.GeneratedProtocolMessageType('PublishAckDgram', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHACKDGRAM,
  '__module__' : 'models_pb2'
  # @@protoc_insertion_point(class_scope:PublishAckDgram)
  })
_sym_db.RegisterMessage(PublishAckDgram)


# @@protoc_insertion_point(module_scope)
